name: landing production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'plane/pawarchive:')"
    steps:
    - uses: actions/checkout@v2
    - name: Deploy application to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_PLANE_PAWARCHIVE }}
        vercel-args: '--prod'
        working-directory: ./frontend/pawarchive-plane